apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      datadog:
        api:
          key: "${DD_API_KEY}"
      jaeger:
        collector_endpoint: "http://jaeger:14268/api/traces"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [datadog, jaeger]
        metrics:
          receivers: [otlp]
          exporters: [datadog]
