apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-policy
  labels:
    app: {{ .Release.Name }}-policy
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-policy
  ports:
    - name: rest
      port: {{ .Values.policy.restPort }}
      targetPort: {{ .Values.policy.restPort }}
    - name: grpc
      port: {{ .Values.policy.grpcPort }}
      targetPort: {{ .Values.policy.grpcPort }}
