apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: {{ .Release.Name }}-proxy
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-proxy
  ports:
    - name: http
      port: {{ .Values.proxy.servicePort }}
      targetPort: {{ .Values.proxy.servicePort }}
    - name: grpc
      port: {{ .Values.proxy.grpcPort }}
      targetPort: {{ .Values.proxy.grpcPort }}
