apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
type: Opaque
data:
  ca.crt: {{ .Values.tls.ca | quote }}
  proxy.crt: {{ .Values.tls.proxyCrt | quote }}
  proxy.key: {{ .Values.tls.proxyKey | quote }}
  graph.crt: {{ .Values.tls.graphCrt | quote }}
  graph.key: {{ .Values.tls.graphKey | quote }}
  policy.crt: {{ .Values.tls.policyCrt | quote }}
  policy.key: {{ .Values.tls.policyKey | quote }}
  verifier.crt: {{ .Values.tls.verifierCrt | quote }}
  verifier.key: {{ .Values.tls.verifierKey | quote }}
