apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-verifier
  labels:
    app: {{ .Release.Name }}-verifier
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-verifier
  ports:
    - name: grpc
      port: {{ .Values.verifier.grpcPort }}
      targetPort: {{ .Values.verifier.grpcPort }}
